In [1]:
all_outcomes = { (i, j): i + j for i in range(1, 7) for j in range(1, 7) } # All the outcomes of throwing two dices
all_outcomes

In [2]:
sumUpSeven = { (i, j): i + j for i in range(1, 7) for j in range(1, 7) if i+j == 7 } # All the outcomes of throwing two dices sum up to 7

In [3]:
sumUpSeven

In [4]:
# We can do it in different way using defaultdict
from collections import defaultdict
dice = defaultdict(list) # defaultdict creates dictionaries with default values when it encounters a new key

In [5]:
for key, value in all_outcomes.items():
  dice[value].append(key)

In [6]:
dice

In [7]:
# Probability of all the outcomes of throwing two dices are
prob_2dice = { key: len(value) / 36.0 for key, value in dice.items() }
prob_2dice

In [8]:
import pandas as pd
d = pd.DataFrame(index=[ (i, j) for i in range(1, 7) for j in range(1, 7) ], columns = ["sm", "dice1", "dice2", "pd1", "pd2", "p"])

In [9]:
d.dice1 = [i[0] for i in d.index]
d.dice2 = [i[1] for i in d.index]
d.sm = list(map(sum, d.index))
d.head(10)

,sm,dice1,dice2,pd1,pd2,p
"(1, 1)",2,1,1,NaN,NaN,NaN
"(1, 2)",3,1,2,NaN,NaN,NaN
"(1, 3)",4,1,3,NaN,NaN,NaN
"(1, 4)",5,1,4,NaN,NaN,NaN
"(1, 5)",6,1,5,NaN,NaN,NaN
"(1, 6)",7,1,6,NaN,NaN,NaN
"(2, 1)",3,2,1,NaN,NaN,NaN
"(2, 2)",4,2,2,NaN,NaN,NaN
"(2, 3)",5,2,3,NaN,NaN,NaN
"(2, 4)",6,2,4,NaN,NaN,NaN

In [10]:
# Probability of unfair dice1
d.loc[d.dice1 <=3, "pd1"] = 1/9 
d.loc[d.dice1 > 3, "pd1"] = 2/9

# Probability of fair dice2
d.pd2 = 1/6

# joint Probability of dice1 and dice2
d.p = d.pd1 * d.pd2
d

,sm,dice1,dice2,pd1,pd2,p
"(1, 1)",2,1,1,0.111111,0.166667,0.0185185
"(1, 2)",3,1,2,0.111111,0.166667,0.0185185
"(1, 3)",4,1,3,0.111111,0.166667,0.0185185
"(1, 4)",5,1,4,0.111111,0.166667,0.0185185
"(1, 5)",6,1,5,0.111111,0.166667,0.0185185
"(1, 6)",7,1,6,0.111111,0.166667,0.0185185
"(2, 1)",3,2,1,0.111111,0.166667,0.0185185
"(2, 2)",4,2,2,0.111111,0.166667,0.0185185
"(2, 3)",5,2,3,0.111111,0.166667,0.0185185
"(2, 4)",6,2,4,0.111111,0.166667,0.0185185
"(2, 5)",7,2,5,0.111111,0.166667,0.0185185
"(2, 6)",8,2,6,0.111111,0.166667,0.0185185
"(3, 1)",4,3,1,0.111111,0.166667,0.0185185
"(3, 2)",5,3,2,0.111111,0.166667,0.0185185
"(3, 3)",6,3,3,0.111111,0.166667,0.0185185
"(3, 4)",7,3,4,0.111111,0.166667,0.0185185
"(3, 5)",8,3,5,0.111111,0.166667,0.0185185
"(3, 6)",9,3,6,0.111111,0.166667,0.0185185
"(4, 1)",5,4,1,0.222222,0.166667,0.037037
"(4, 2)",6,4,2,0.222222,0.166667,0.037037
"(4, 3)",7,4,3,0.222222,0.166667,0.037037
"(4, 4)",8,4,4,0.222222,0.166667,0.037037
"(4, 5)",9,4,5,0.222222,0.166667,0.037037
"(4, 6)",10,4,6,0.222222,0.166667,0.037037
"(5, 1)",6,5,1,0.222222,0.166667,0.037037
"(5, 2)",7,5,2,0.222222,0.166667,0.037037
"(5, 3)",8,5,3,0.222222,0.166667,0.037037
"(5, 4)",9,5,4,0.222222,0.166667,0.037037
"(5, 5)",10,5,5,0.222222,0.166667,0.037037
"(5, 6)",11,5,6,0.222222,0.166667,0.037037
"(6, 1)",7,6,1,0.222222,0.166667,0.037037
"(6, 2)",8,6,2,0.222222,0.166667,0.037037
"(6, 3)",9,6,3,0.222222,0.166667,0.037037
"(6, 4)",10,6,4,0.222222,0.166667,0.037037
"(6, 5)",11,6,5,0.222222,0.166667,0.037037
"(6, 6)",12,6,6,0.222222,0.166667,0.037037

In [11]:
# Probability mass function of sum of two dices
d.groupby("sm")["p"].sum()